version: "3.9"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=Jony
      - HTTP_PASSWORD=password
    ports:
      - 8081:8081
    depends_on:
      - redis
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: Jony
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis-data:
  postgres-data: